//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManCaveLeague
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueGame
    {
        public int LeagueGameId { get; set; }
        public int RFIDCardId { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ConsoleId { get; set; }
        public Nullable<System.DateTime> UseDate { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> LeagueId { get; set; }
    }
}
