//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManCaveLeague
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MCLEntities : DbContext
    {
        public MCLEntities()
            : base("name=MCLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<League> Leagues { get; set; }
        public virtual DbSet<LeagueJudge> LeagueJudges { get; set; }
        public virtual DbSet<LeagueMaster> LeagueMasters { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerGame> PlayerGames { get; set; }
        public virtual DbSet<PlayerMaster> PlayerMasters { get; set; }
        public virtual DbSet<Rank> Ranks { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Tier> Tiers { get; set; }
        public virtual DbSet<TierType> TierTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<View_AllGames> View_AllGames { get; set; }
        public virtual DbSet<View_AllJudges> View_AllJudges { get; set; }
        public virtual DbSet<View_AllLegueRules> View_AllLegueRules { get; set; }
        public virtual DbSet<View_AllGamesOfLeague> View_AllGamesOfLeague { get; set; }
        public virtual DbSet<View_PlayerInfo> View_PlayerInfo { get; set; }
    }
}
