//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManCaveLeague
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerGame
    {
        public int PlayerGameId { get; set; }
        public Nullable<int> PlayerMasterId { get; set; }
        public string RecordingFileName { get; set; }
        public Nullable<System.DateTime> GameStartTime { get; set; }
        public Nullable<System.DateTime> GameEndTime { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> TierId { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<int> GamePoints { get; set; }
        public Nullable<bool> IsMarked { get; set; }
        public Nullable<int> MarkedById { get; set; }
        public Nullable<System.DateTime> MarkedAt { get; set; }
        public string ConsoleName { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Result Result { get; set; }
        public virtual Tier Tier { get; set; }
        public virtual User User { get; set; }
        public virtual PlayerMaster PlayerMaster { get; set; }
    }
}
