//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManCaveLeague
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PlayerInfo
    {
        public string PlayerName { get; set; }
        public int PlayerId { get; set; }
        public Nullable<int> PlayerUserId { get; set; }
        public Nullable<int> SmartLaunchDBId { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public int PlayerMasterId { get; set; }
        public Nullable<int> TierId { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> TotalPoints { get; set; }
        public bool PromoEnabled { get; set; }
        public Nullable<bool> IsPromoBlock { get; set; }
    }
}
