//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManCaveLeague
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AllGamesOfLeague
    {
        public int LeagueMasterId { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> WinPoints { get; set; }
        public Nullable<int> LoosePoints { get; set; }
        public Nullable<int> TiePoints { get; set; }
        public Nullable<int> InvalidPoints { get; set; }
        public Nullable<int> MaximumGamePlayTime { get; set; }
        public int Expr1 { get; set; }
        public string Title { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
    }
}
