//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManCaveLeague
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AllJudges
    {
        public int LeagueJudgeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public string LoginId { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public string League { get; set; }
        public Nullable<int> GameId { get; set; }
        public string Game { get; set; }
        public Nullable<int> LeagueMasterId { get; set; }
    }
}
